### PR TITLE
New algorithms are added to uadk_provider.

### PR DESCRIPTION
**Pull request by patch-king**

### CODE REVIEW

**Comment by gaozhangfei** [comment]
build warning?

uadk_prov_pkey.c: In function 'uadk_prov_ecc_init':
uadk_prov_pkey.c:813:36: warning: passing argument 1 of 'wd_ecc_init2_' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  813 |                 ret = wd_ecc_init2(alg_name, SCHED_POLICY_RR, TASK_HW);
      |                                    ^~~~~~~~
/usr/local/include/uadk/wd_ecc.h:454:25: note: expected 'char *' but argument is of type 'const char *'
  454 | int wd_ecc_init2_(char *alg, __u32 sched_type, int task_type, struct wd_ctx_params *ctx_params);
      |                   ~~~~~~^~~
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -I/usr/local/include -DOPENSSL_SUPPRESS_DEPRECATED -Wall -MT uadk_provider_la-uadk_prov_bio.lo -MD -MP -MF .deps/uadk_provider_la-uadk_prov_bio.Tpo -c uadk_prov_bio.c -o uadk_provider_la-uadk_prov_bio.o >/dev/null 2>&1
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -I/usr/local/include -DOPENSSL_SUPPRESS_DEPRECATED -Wall -MT uadk_provider_la-uadk_prov_der_writer.lo -MD -MP -MF .deps/uadk_provider_la-uadk_prov_der_writer.Tpo -c uadk_prov_der_writer.c -o uadk_provider_la-uadk_prov_der_writer.o >/dev/null 2>&1
mv -f .deps/uadk_engine_la-uadk_utils.Tpo .deps/uadk_engine_la-uadk_utils.Plo
In file included from uadk_prov_ecdh_exch.c:28:
uadk_prov_pkey.h:463:26: warning: 'get_default_ecdh_keyexch' defined but not used [-Wunused-function]
  463 | static UADK_PKEY_KEYEXCH get_default_##nm##_keyexch(void)               \
      |                          ^~~~~~~~~~~~
uadk_prov_ecdh_exch.c:78:1: note: in expansion of macro 'UADK_PKEY_KEYEXCH_DESCR'
   78 | UADK_PKEY_KEYEXCH_DESCR(ecdh, ECDH);
      | ^~~~~~~~~~~~~~~~~~~~~~~
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -I/usr/local/include -DOPENSSL_SUPPRESS_DEPRECATED -Wall -MT uadk_provider_la-uadk_prov_packet.lo -MD -MP -MF .deps/uadk_provider_la-uadk_prov_packet.Tpo -c uadk_prov_packet.c -o uadk_provider_la-uadk_prov_packet.o >/dev/null 2>&1
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -I/usr/local/include -DOPENSSL_SUPPRESS_DEPRECATED -Wall -MT uadk_provider_la-uadk_prov_init.lo -MD -MP -MF .deps/uadk_provider_la-uadk_prov_init.Tpo -c uadk_prov_init.c -o uadk_provider_la-uadk_prov_init.o >/dev/null 2>&1
uadk_prov_cipher.c: In function 'uadk_prov_cipher_soft_final':
uadk_prov_cipher.c:339:52: warning: passing argument 3 of 'EVP_CipherFinal_ex' from incompatible pointer type [-Wincompatible-pointer-types]
  339 |         if (!EVP_CipherFinal_ex(priv->sw_ctx, out, &sw_final_len)) {
      |                                                    ^~~~~~~~~~~~~
      |                                                    |
      |                                                    size_t * {aka long unsigned int *}
In file included from /usr/local/include/openssl/rand.h:23,
                 from /usr/local/include/openssl/engine.h:29,
                 from uadk.h:20,
                 from uadk_prov_cipher.c:28:
/usr/local/include/openssl/evp.h:798:36: note: expected 'int *' but argument is of type 'size_t *' {aka 'long unsigned int *'}
  798 |                               int *outl);
      |                               ~~~~~^~~~
uadk_prov_aead.c: In function 'uadk_do_aead_sync_inner':
uadk_prov_aead.c:308:23: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  308 |         priv->req.src = in;
      |                       ^
uadk_prov_cipher.c: In function 'uadk_prov_do_cipher':
uadk_prov_cipher.c:806:53: warning: passing argument 3 of 'uadk_prov_cipher_soft_work' from incompatible pointer type [-Wincompatible-pointer-types]
  806 |         ret = uadk_prov_cipher_soft_work(priv, out, &outlint, in, inlen);
      |                                                     ^~~~~~~~
      |                                                     |
      |                                                     size_t * {aka long unsigned int *}
uadk_prov_cipher.c:316:44: note: expected 'int *' but argument is of type 'size_t *' {aka 'long unsigned int *'}
  316 |                                       int *outl, const unsigned char *in, size_t len)
      |                                       ~~~~~^~~~
In file included from uadk_prov_sm2.c:29:
uadk_prov_pkey.h:392:30: warning: 'get_default_sm2_asym_cipher' defined but not used [-Wunused-function]
  392 | static UADK_PKEY_ASYM_CIPHER get_default_##nm##_asym_cipher(void)       \
      |                              ^~~~~~~~~~~~
uadk_prov_sm2.c:37:1: note: in expansion of macro 'UADK_PKEY_ASYM_CIPHER_DESCR'
   37 | UADK_PKEY_ASYM_CIPHER_DESCR(sm2, SM2);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
uadk_prov_pkey.h:296:28: warning: 'get_default_sm2_signature' defined but not used [-Wunused-function]
  296 | static UADK_PKEY_SIGNATURE get_default_##nm##_signature(void)   \
      |                            ^~~~~~~~~~~~
uadk_prov_sm2.c:36:1: note: in expansion of macro 'UADK_PKEY_SIGNATURE_DESCR'
   36 | UADK_PKEY_SIGNATURE_DESCR(sm2, SM2);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
uadk_prov_aead.c: In function 'uadk_prov_aead_ctx_init':
uadk_prov_aead.c:203:33: warning: storing the address of local variable 'params' in '*priv.setup.sched_param' [-Wdangling-pointer=]
  203 |         priv->setup.sched_param = &params;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
uadk_prov_aead.c:181:29: note: 'params' declared here
  181 |         struct sched_params params = {0};
      |                             ^~~~~~
uadk_prov_aead.c:181:29: note: 'priv' declared here
In file included from uadk_prov_dh.c:29:
uadk_prov_pkey.h:463:26: warning: 'get_default_dh_keyexch' defined but not used [-Wunused-function]
  463 | static UADK_PKEY_KEYEXCH get_default_##nm##_keyexch(void)               \
      |                          ^~~~~~~~~~~~
uadk_prov_dh.c:60:1: note: in expansion of macro 'UADK_PKEY_KEYEXCH_DESCR'
   60 | UADK_PKEY_KEYEXCH_DESCR(dh, DH);


master branch 也有, 能一起帮忙解决下？
uadk_prov_pkey.h:376:30: warning: 'get_default_sm2_asym_cipher' defined but not used [-Wunused-function]
  376 | static UADK_PKEY_ASYM_CIPHER get_default_##nm##_asym_cipher(void)       \
      |                              ^~~~~~~~~~~~
uadk_prov_sm2.c:37:1: note: in expansion of macro 'UADK_PKEY_ASYM_CIPHER_DESCR'
   37 | UADK_PKEY_ASYM_CIPHER_DESCR(sm2, SM2);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
uadk_prov_pkey.h:280:28: warning: 'get_default_sm2_signature' defined but not used [-Wunused-function]
  280 | static UADK_PKEY_SIGNATURE get_default_##nm##_signature(void)   \
      |                            ^~~~~~~~~~~~
uadk_prov_sm2.c:36:1: note: in expansion of macro 'UADK_PKEY_SIGNATURE_DESCR'
   36 | UADK_PKEY_SIGNATURE_DESCR(sm2, SM2);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from uadk_prov_dh.c:29:
uadk_prov_pkey.h:447:26: warning: 'get_default_dh_keyexch' defined but not used [-Wunused-function]
  447 | static UADK_PKEY_KEYEXCH get_default_##nm##_keyexch(void)               \
      |                          ^~~~~~~~~~~~
uadk_prov_dh.c:60:1: note: in expansion of macro 'UADK_PKEY_KEYEXCH_DESCR'
   60 | UADK_PKEY_KEYEXCH_DESCR(dh, DH);
      | ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by gaozhangfei** [comment]
我这边跑sanity_test, 不确定可是我环境问题，
2064229BFFFF0000:error:1C8000BF:Provider routines:ossl_prov_drbg_generate:generate error:providers/implementations/rands/drbg.c:685:
2064229BFFFF0000:error:1C8000BF:Provider routines:ossl_drbg_get_seed:generate error:providers/implementations/rands/drbg.c:180:
2064229BFFFF0000:error:1C8000BD:Provider routines:ossl_prov_drbg_instantiate:error retrieving entropy:providers/implementations/rands/drbg.c:456:
2064229BFFFF0000:error:1200006C:random number generator:rand_new_drbg:error instantiating drbg:crypto/rand/rand_lib.c:607:


master 分支
20049F95FFFF0000:error:030000BD:digital envelope routines:EVP_EncryptUpdate:update error:crypto/evp/evp_enc.c:690:
20049F95FFFF0000:error:1C8000BC:Provider routines:ossl_prov_drbg_instantiate:error instantiating drbg:providers/implementations/rands/drbg.c:463:
20049F95FFFF0000:error:1200006C:random number generator:rand_new_drbg:error instantiating drbg:crypto/rand/rand_lib.c:607:

**Comment by gaozhangfei** [comment]
223 合入之前， build 没问题，sanity_test 也没问题

223 合入后，即 master 分支 build warning + sanity_test warning
build warning
In file included from uadk_prov_sm2.c:29:
uadk_prov_pkey.h:376:30: warning: 'get_default_sm2_asym_cipher' defined but not used [-Wunused-function]
  376 | static UADK_PKEY_ASYM_CIPHER get_default_##nm##_asym_cipher(void)       \
      |                              ^~~~~~~~~~~~
uadk_prov_sm2.c:37:1: note: in expansion of macro 'UADK_PKEY_ASYM_CIPHER_DESCR'
   37 | UADK_PKEY_ASYM_CIPHER_DESCR(sm2, SM2);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
uadk_prov_pkey.h:280:28: warning: 'get_default_sm2_signature' defined but not used [-Wunused-function]
  280 | static UADK_PKEY_SIGNATURE get_default_##nm##_signature(void)   \
      |                            ^~~~~~~~~~~~
uadk_prov_sm2.c:36:1: note: in expansion of macro 'UADK_PKEY_SIGNATURE_DESCR'
   36 | UADK_PKEY_SIGNATURE_DESCR(sm2, SM2);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from uadk_prov_dh.c:29:
uadk_prov_pkey.h:447:26: warning: 'get_default_dh_keyexch' defined but not used [-Wunused-function]
  447 | static UADK_PKEY_KEYEXCH get_default_##nm##_keyexch(void)               \
      |                          ^~~~~~~~~~~~
uadk_prov_dh.c:60:1: note: in expansion of macro 'UADK_PKEY_KEYEXCH_DESCR'
   60 | UADK_PKEY_KEYEXCH_DESCR(dh, DH);
      | ^~~~~~~~~~~~~~~~~~~~~~~

sanity_test warning:
20143C98FFFF0000:error:030000BD:digital envelope routines:EVP_EncryptUpdate:update error:crypto/evp/evp_enc.c:690:
20143C98FFFF0000:error:1C8000BC:Provider routines:ossl_prov_drbg_instantiate:error instantiating drbg:providers/implementations/rands/drbg.c:463:
20143C98FFFF0000:error:1200006C:random number generator:rand_new_drbg:error instantiating drbg:crypto/rand/rand_lib.c:607:

pr 225: build warning + sanity_test warning

能否先把 master 上的build warning + sanity_test warning 解决掉, release
这个pr 要是来不及 等release 后再合？

**Comment by CaptainMiaow** [comment]
> 223 合入之前， build 没问题，sanity_test 也没问题
> 
> 223 合入后，即 master 分支 build warning + sanity_test warning build warning In file included from uadk_prov_sm2.c:29: uadk_prov_pkey.h:376:30: warning: 'get_default_sm2_asym_cipher' defined but not used [-Wunused-function] 376 | static UADK_PKEY_ASYM_CIPHER get_default_##nm##_asym_cipher(void) | ^~~~~~~~~~~~ uadk_prov_sm2.c:37:1: note: in expansion of macro 'UADK_PKEY_ASYM_CIPHER_DESCR' 37 | UADK_PKEY_ASYM_CIPHER_DESCR(sm2, SM2); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~ uadk_prov_pkey.h:280:28: warning: 'get_default_sm2_signature' defined but not used [-Wunused-function] 280 | static UADK_PKEY_SIGNATURE get_default_##nm##_signature(void) | ^~~~~~~~~~~~ uadk_prov_sm2.c:36:1: note: in expansion of macro 'UADK_PKEY_SIGNATURE_DESCR' 36 | UADK_PKEY_SIGNATURE_DESCR(sm2, SM2); | ^~~~~~~~~~~~~~~~~~~~~~~~~ In file included from uadk_prov_dh.c:29: uadk_prov_pkey.h:447:26: warning: 'get_default_dh_keyexch' defined but not used [-Wunused-function] 447 | static UADK_PKEY_KEYEXCH get_default_##nm##_keyexch(void) | ^~~~~~~~~~~~ uadk_prov_dh.c:60:1: note: in expansion of macro 'UADK_PKEY_KEYEXCH_DESCR' 60 | UADK_PKEY_KEYEXCH_DESCR(dh, DH); | ^~~~~~~~~~~~~~~~~~~~~~~
> 
> sanity_test warning: 20143C98FFFF0000:error:030000BD:digital envelope routines:EVP_EncryptUpdate:update error:crypto/evp/evp_enc.c:690: 20143C98FFFF0000:error:1C8000BC:Provider routines:ossl_prov_drbg_instantiate:error instantiating drbg:providers/implementations/rands/drbg.c:463: 20143C98FFFF0000:error:1200006C:random number generator:rand_new_drbg:error instantiating drbg:crypto/rand/rand_lib.c:607:
> 
> pr 225: build warning + sanity_test warning
> 
> 能否先把 master 上的build warning + sanity_test warning 解决掉, release 这个pr 要是来不及 等release 后再合？

OK

**Review by Liulongfang — APPROVED** [review]
looks good to me

**Comment by gaozhangfei** [comment]
需要重新提交，目标devel branch？这个是master

**Comment by gaozhangfei** [comment]
In file included from uadk_prov_pkey.h:36,
                 from uadk_prov_pkey.c:19:
uadk_prov_pkey.c: In function 'uadk_prov_ecc_init':
uadk_prov_pkey.c:812:36: warning: passing argument 1 of 'wd_ecc_init2_' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  812 |                 ret = wd_ecc_init2(alg_name, SCHED_POLICY_RR, TASK_HW);
      |                                    ^~~~~~~~
/usr/local/include/uadk/wd_ecc.h:454:25: note: expected 'char *' but argument is of type 'const char *'
  454 | int wd_ecc_init2_(char *alg, __u32 sched_type, int task_type, struct wd_ctx_params *ctx_params);
      |                   ~~~~~~^~~
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -I/usr/local/include -DOPENSSL_SUPPRESS_DEPRECATED -Wall -MT uadk_provider_la-uadk_prov_der_writer.lo -MD -MP -MF .deps/uadk_provider_la-uadk_prov_der_writer.Tpo -c uadk_prov_der_writer.c -o uadk_provider_la-uadk_prov_der_writer.o >/dev/null 2>&1
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -I/usr/local/include -DOPENSSL_SUPPRESS_DEPRECATED -Wall -MT uadk_provider_la-uadk_prov_packet.lo -MD -MP -MF .deps/uadk_provider_la-uadk_prov_packet.Tpo -c uadk_prov_packet.c -o uadk_provider_la-uadk_prov_packet.o >/dev/null 2>&1
uadk_prov_aead.c: In function 'uadk_do_aead_sync_inner':
uadk_prov_aead.c:308:23: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  308 |         priv->req.src = in;
      |                       ^
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -I/usr/local/include -DOPENSSL_SUPPRESS_DEPRECATED -Wall -MT uadk_provider_la-uadk_prov_init.lo -MD -MP -MF .deps/uadk_provider_la-uadk_prov_init.Tpo -c uadk_prov_init.c -o uadk_provider_la-uadk_prov_init.o >/dev/null 2>&1
uadk_prov_aead.c: In function 'uadk_prov_aead_ctx_init':
uadk_prov_aead.c:203:33: warning: storing the address of local variable 'params' in '*priv.setup.sched_param' [-Wdangling-pointer=]
  203 |         priv->setup.sched_param = &params;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
uadk_prov_aead.c:181:29: note: 'params' declared here
  181 |         struct sched_params params = {0};
      |                             ^~~~~~
uadk_prov_aead.c:181:29: note: 'priv' declared here

**Pull request closed without merging**
