### PR TITLE
engine: fix engine can't work under hybrid mode

### PR DESCRIPTION
**Pull request by lin755**
If hpre works in no-sva mode, and sec works in sva mode,
it will init hpre device first and return straightly, this
casuse sec not initialized correctly. So uadk engine should
init for both sva and no-sva device.

Signed-off-by: Wenkai Lin <linwenkai6@hisilicon.com>

### CODE REVIEW

**Comment by CaptainMiaow** [comment]
您发来的邮件已收到！

**Comment by gaozhangfei** [comment]
Confused, only works in single mode, either sva or no-sva, 
"If hpre works in no-sva mode, and sec works in sva mode" what this mean?

**Comment by lin755** [comment]
> Confused, only works in single mode, either sva or no-sva, "If hpre works in no-sva mode, and sec works in sva mode" what this mean?

hpre device works in no sva mode, sec device works in sva mode.
user can do like this:
insmod hisi_sec2 uacce_mode=1
insmod hisi_hpre uacce_mode=2

**Comment by lin755** [comment]
before: bind_fn return after find hpre device
after: bind_fn_kae first,then bind_fn_uadk,
ps: uadk modify wd_get_accel_dev to prevent return non-sva device，see more detals:
https://github.com/Linaro/uadk/commit/ed40cdef214d5f816596ab0d538932875fc876db

**Comment by gaozhangfei** [comment]
If both sva and no-sva are enabled.
Then both async_module_init_v1() and async_module_init() are enabled.
Both engine_init_child_at_fork_handler_v1 and engine_init_child_at_fork_handler are called.
Any conflict?

#ifdef KAE
        if (uadk_cipher_nosva || uadk_digest_nosva || uadk_rsa_nosva ||
            uadk_dh_nosva) {
                async_module_init_v1();
                pthread_atfork(NULL, NULL, engine_init_child_at_fork_handler_v1);
        }
#endif
        if (uadk_cipher || uadk_digest || uadk_rsa || uadk_dh || uadk_ecc) {
                async_module_init(); 
                pthread_atfork(NULL, NULL, engine_init_child_at_fork_handler);
        }

**Pull request merged**
